# Generated by Django 5.0.1 on 2024-01-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prasath", "0002_alter_photo_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="picture/")),
            ],
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
