# Generated by Django 5.0.1 on 2024-01-07 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prasath", "0003_image_delete_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Image", "verbose_name_plural": "Image"},
        ),
    ]
