# Generated by Django 5.0.1 on 2024-01-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prasath", "0004_alter_image_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="picture/")),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
            },
        ),
    ]
