# Generated by Django 5.0.1 on 2024-01-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prasath", "0007_delete_staff_delete_staff1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/")),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
