# Generated by Django 5.0.1 on 2024-01-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prasath", "0008_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("register_id", models.CharField(max_length=100)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=100)),
                ("paid", models.BooleanField(default=False)),
            ],
        ),
    ]
