# Generated by Django 5.0.1 on 2024-01-29 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prasath", "0010_alter_registration_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="register_id",
        ),
    ]
