# Generated by Django 5.0.1 on 2024-01-30 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prasath", "0012_registration_email_alter_registration_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="paid",
        ),
    ]
